export const ACTIONS = {
  NEW_USER_DATA: 'NEW_USER_DATA',
  REMOVE_USER_DATA: 'DROP_USER_DATA',
  NEW_ORDERS: 'NEW_ORDERS_DATA',
  REMOVE_FROM_ORDERS: 'REMOVE_FROM_ORDERS_DATA',
  APPEND_ORDERS: 'ADD_NEW_ORDER_TO_ORDERS_DATA',
  SIGN_IN: 'USER_LOG_IN',
  LOG_OFF: 'USER_LOG_OFF',
  NEW_CURRENT_ORDER: 'NEW_CURRENT_ORDER'
}